### ISSUE TITLE
Trying to use this

### ISSUE THREAD

**Issue by danac78** [Moshibit/RenPy_automatic_translations#1]
So, I installed Python, pycountry (either a typo or missing something with what you typed in readme), and textblob. 

1. create a tl with spanish as a text.
2. Type in python auto_translate.py es (based on what I am understanding from the readme). (even put the translate folder as es, but get "es is not supported")

But it is coming back with English in the new section.

**Comment by Arku3S** [comment]
I also got a message that the language is not supported, but it works fine.
The language must be entered in parentheses as follows:

python auto_translate.py [es]

Unfortunately the translation is slow.

**Comment by danac78** [comment]
I can deal with slowness. It was an error on my part reading the instruction. I thought the [language] was a placeholder in a line so was typing python auto_translate.py es rather than es in brackets.
